---
title: "Logistic Regression Assignment"
author: "Keith Engwall"
date: "4/12/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(effects)
library(caTools)
library(ROCR)
```

```{r}
setwd("~/Documents/introdatascience/logistic_regression")
NH11 <- readRDS("dataSets/NatHealth2011.rds")
labs <- attributes(NH11)$labels
labs
```
```{r}
# collapse all missing values to NA
NH11$hypev <- factor(NH11$hypev, levels=c("2 No", "1 Yes"))
str(NH11$hypev) # check stucture of hypev
levels(NH11$hypev) # check levels of hypev
```

```{r}
# run our regression model
hyp.out <- glm(hypev~age_p+sex+sleep+bmi,
              data=NH11, family="binomial")
coef(summary(hyp.out))
```

```{r}
##   One solution is to transform the coefficients to make them easier to
##   interpret

hyp.out.tab <- coef(summary(hyp.out))
hyp.out.tab[, "Estimate"] <- exp(coef(hyp.out))
hyp.out.tab
```


```{r}
# Create a dataset with predictors set at desired levels
predDat <- with(NH11,
                expand.grid(age_p = c(33, 63),
                            sex = "2 Female",
                            bmi = mean(bmi, na.rm = TRUE),
                            sleep = mean(sleep, na.rm = TRUE)))
```

```{r}
# predict hypertension at those levels
cbind(predDat, predict(hyp.out, type = "response",
                       se.fit = TRUE, interval="confidence",
                       newdata = predDat))
```

```{r}
plot(allEffects(hyp.out))
```

```{r}
str(NH11$r_maritl)
levels(NH11$r_maritl)
```
```{r}
str(NH11$everwrk)
levels(NH11$everwrk)
```

```{r}
NH11Work = subset(NH11, !is.na(NH11$everwrk))
NH11Work$everwrk <- factor(NH11Work$everwrk, levels=c("2 No", "1 Yes"))
NH11Work <- subset(NH11Work, !is.na(NH11Work$everwrk))
NH11Work$everwrkTF <- ifelse(NH11Work$everwrk=="1 Yes", 1, 0)
split <- sample.split(NH11Work$everwrkTF, SplitRatio = 0.65)
NH11Train = subset(NH11Work, split == TRUE)
NH11Test = subset(NH11Work, split == FALSE)
```

```{r}
workLog = glm(everwrkTF ~ age_p + r_maritl, data = NH11Train, family = binomial)
summary(workLog)
```

```{r}
workLog.tab <- coef(summary(workLog))
workLog.tab[,"Estimate"] <- exp(coef(workLog))
workLog.tab
```



```{r}
library(effects)
plot(allEffects(workLog))
summary(allEffects(workLog))
```



